In [4]:
from tensorflow.keras.models import load_model
import pandas as pd
import numpy as np
import dict_map as dm

filepath = './models/saved_model'
# Load the model
model = load_model(filepath, compile = True)

In [5]:
df = pd.read_csv('Daten/trainingdata300.csv',escapechar="\\",sep=",",error_bad_lines=False,warn_bad_lines=False)
# df = df.head(1000)
token2idx, idx2token = dm.get_dict_map(df, 'token')
tag2idx, idx2tag = dm.get_dict_map(df, 'tag')

df['Word_idx'] = df['Wort'].map(token2idx)
df['Tag_idx'] = df['Attribut'].map(tag2idx)

df_group = df.groupby(by = ['satzId'], as_index=False)['Wort', 'Attribut', 'Word_idx', 'Tag_idx'].agg(lambda x: list(x))
#df_group
import pad_train_test as ptt
train_tokens, val_tokens, test_tokens, train_tags, val_tags, test_tags = ptt.get_pad_train_test_val(df_group, df, tag2idx)

<ipython-input-5-ffa0064ed6ee>:9: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df_group = df.groupby(by = ['satzId'], as_index=False)['Wort', 'Attribut', 'Word_idx', 'Tag_idx'].agg(lambda x: list(x))
train_tokens length: 26331 
train_tags length: 26331 
test_tokens length: 3902 
test_tags: 3902 
val_tokens: 8778 
val_tags: 8778


In [4]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(test_tokens, np.array(test_tags), batch_size=300)
print("test loss, test acc:", results)

# Generate predictions (probabilities -- the output of the last layer)
# on new data using `predict`
print("Generate predictions for 3 samples")
predictions = model.predict(test_tokens[:3])
print("predictions shape:", predictions.shape)

Evaluate on test data
14/14 [==============================] - 36s 2s/step - loss: 9.8864 - accuracy: 5.8517e-04
test loss, test acc: [9.88640022277832, 0.0005851699970662594]
Generate predictions for 3 samples
predictions shape: (3, 300, 8)


In [6]:
predictions = model.predict(test_tokens)
classes = np.argmax(predictions, axis = 1)

In [7]:
# print(predictions)
print(classes[0])

[  0   0   0   0 284   0   0   0]


In [13]:
df.groupby('Attribut').count()

satzId     Wort  Word_idx  Tag_idx
Attribut                                          
B-Brand          67464    67464     67464    67464
B-Modelnumber    33296    33115     33296    33296
E-Brand           4521     4521      4521     4521
E-Modelnumber     7143     7143      7143     7143
I-Brand           1068     1068      1068     1068
I-Modelnumber     7123     7123      7123     7123
O              4807866  4807703   4807866  4807866

In [12]:
df.isna().sum()

satzId        0
Wort        344
Attribut      3
Word_idx      0
Tag_idx       0
dtype: int64

In [10]:
val_tokens
val_tags

0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 