In [4]:
from tensorflow.keras.models import load_model
import pandas as pd
import numpy as np
import dict_map as dm

filepath = './models/saved_model'
# Load the model
model = load_model(filepath, compile = True)

In [7]:
df = pd.read_csv('Daten/trainingdata300.csv',escapechar="\\",sep=",",error_bad_lines=False,warn_bad_lines=False)
# df = df.head(1000)
token2idx, idx2token = dm.get_dict_map(df, 'token')
tag2idx, idx2tag = dm.get_dict_map(df, 'tag')

df['Word_idx'] = df['Wort'].map(token2idx)
df['Tag_idx'] = df['Attribut'].map(tag2idx)

df_group = df.groupby(by = ['satzId'], as_index=False)['Wort', 'Attribut', 'Word_idx', 'Tag_idx'].agg(lambda x: list(x))
#df_group
import pad_train_test as ptt
train_tokens, val_tokens, test_tokens, train_tags, val_tags, test_tags = ptt.get_pad_train_test_val(df_group, df, tag2idx)

<ipython-input-7-ffa0064ed6ee>:9: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df_group = df.groupby(by = ['satzId'], as_index=False)['Wort', 'Attribut', 'Word_idx', 'Tag_idx'].agg(lambda x: list(x))
train_tokens length: 26331 
train_tags length: 26331 
test_tokens length: 3902 
test_tags: 3902 
val_tokens: 8778 
val_tags: 8778


In [20]:
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(test_tokens, batch_size=300)
print("test loss, test acc:", results)

# Generate predictions (probabilities -- the output of the last layer)
# on new data using `predict`
print("Generate predictions for 3 samples")
predictions = model.predict(test_tokens[:3])
print("predictions shape:", predictions.shape)

Evaluate on test data
14/14 [==============================] - 15s 1s/step - loss: 0.0000e+00 - accuracy: 0.0000e+00
test loss, test acc: [0.0, 0.0]
Generate predictions for 3 samples
predictions shape: (3, 300, 8)


In [11]:
predictions = model.predict(val_tokens)
classes = np.argmax(predictions, axis = 1)

[[[1.91824120e-02 2.53741127e-02 4.52771224e-02 ... 1.17428742e-01
   4.16776612e-02 3.76266651e-02]
  [3.00884433e-03 5.43956785e-03 1.74638368e-02 ... 1.01364635e-01
   1.25718610e-02 1.59259364e-02]
  [7.95211585e-04 1.78039621e-03 8.93289037e-03 ... 7.97059238e-02
   4.82988544e-03 9.33481660e-03]
  ...
  [9.12222106e-07 1.20554080e-06 1.11399222e-05 ... 1.03247276e-05
   3.17649187e-06 4.29520333e-06]
  [9.29756141e-07 1.23080144e-06 1.12842990e-05 ... 1.04241262e-05
   3.21554990e-06 4.34159074e-06]
  [9.48384525e-07 1.25750341e-06 1.14367940e-05 ... 1.05326035e-05
   3.25724250e-06 4.39200721e-06]]

 [[1.94539465e-02 2.58568842e-02 4.57816124e-02 ... 1.18161701e-01
   4.21573706e-02 3.79312001e-02]
  [3.11252382e-03 5.66580845e-03 1.80057641e-02 ... 1.03332750e-01
   1.29938629e-02 1.62796453e-02]
  [8.61889974e-04 1.94158894e-03 9.59766284e-03 ... 8.46692398e-02
   5.22668520e-03 9.99625493e-03]
  ...
  [9.22613651e-07 1.21994003e-06 1.12597754e-05 ... 1.04507599e-05
   3.21606

In [15]:
# print(predictions)
print(classes)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
val_tokens
val_tags

0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 